### ISSUE TITLE
That's not ascii

### ISSUE THREAD

**Issue by HybridDog** [dysfunc/ascii-emoji#3]
The emojis consist of Unicode characters.
See https://en.wikipedia.org/wiki/ASCII and https://en.wikipedia.org/wiki/Unicode

**Comment by dysfunc** [comment]
yes, I'm aware. however, people aren't searching "unicode" they are looking for "ascii" not understanding the difference - better SEO :)

**Comment by HybridDog** [comment]
You could add this information in the Readme,
when those people read it, they may begin understanding the difference.

**Comment by dysfunc** [comment]
https://github.com/dysfunc/ascii-emoji/commit/c24ea24162fdcfcde778f5d1098512cfab7dc287

**Comment by twneale** [comment]
༼⍨༽

**Comment by HybridDog** [comment]
‪
