### ISSUE TITLE
encodings

### ISSUE THREAD

**Issue by SteveDoyle2** [dysfunc/ascii-emoji#6]
I really like the ಠ益ಠ face, but am having trouble with the encoding.  Unicode is not an encoding, it's an all encompassing group of the various encodings (e.g., UTF-8, UTF-8-BOM, UTF-16, UTF-32, etc.).

Any idea what type it is?

**Comment by dysfunc** [comment]
I don't know the originating set but I would suggest only using UTF-8 as UTF-16 and UTF-32 are not recommended. UTF-16 will give you problems and even if you use UTF-32 you'll still most likely see issues. If this is something you're using on the web I would highly recommend using UTF-8 only.

This article has some decent points - http://utf8everywhere.org/

**Comment by SteveDoyle2** [comment]
I don't disagree, but it's not UTF-8.  That was my first guess.
